### ISSUE TITLE
Cannot login with credentials to qBitorrent

### ISSUE THREAD

**Issue by markspivey** [GreenFrogSB/LMDS#10]
A few others have noted that it's not possible to log into the web-ui of qBittorrent with the default username and password.

It turns out that the default username/login is actually correct, but there's an inherent issue with libseccomp2 (2.3.3/the distro version). 

libseccomp2 needs to be updated to > 2.4.4 for users to be able to login correctly. 

Ref: https://superuser.com/questions/1633210/qbittorrent-docker-webui-nothing-happen-on-default-password

**Comment by GreenFrogSB** [comment]
OK, LMDS updated but that will only work for new fresh OS installations from now on. I incorporated libseccomp2_2.5.1 with the script. 

If you want to fix your issue on existing installation do below:  
```
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
```

**Comment by SapneshNaik** [comment]
@GreenFrogSB looks like this issue is still present, and manually upgrading libseccomp2  as per your above comment worked. Please implement the above change into your latest code. Thanks
