### ISSUE TITLE
Add dns tag to compose file. Different stack with pihole interferes and the LMD stack containers not getting connected

### ISSUE THREAD

**Issue by Adil-MohammedK** [GreenFrogSB/LMDS#12]
If any another stack with Pi hole is present, it interferes with the LMDS stack and none of the containers i,e, Jackett, Radarr, Deluge are getting connected to the internet. 

This can be solved by adding dns tag to the compose file

`.......
jackett:
  image: linuxserver/jackett
  container_name: jackett
  dns
     - 8.8.8.8
     - 1.1.1.1
   environment:
   ........`

**Comment by GreenFrogSB** [comment]
Make sure Pi-hole is properly configured in the local network, so your Pi stack receives proper DNS addresses allowing containers to resolve DNS calls . Examine pi-hole blocking list to determine if traffic is allowed to all addresses, you think are ok to go out that originating from pi stack. You can also adopt solution above by modifying docker-compose.yml file and add customer DNS records to each container for troubleshooting.

**Comment by bustedbyte** [comment]
Can you put an example, of a proper config option for pi-hole to grant IP's to the PI stack? I have pi-hole configured for the network but I'm running into this as well, seems like the connected servers are not reaching out for network IP's

**Comment by GreenFrogSB** [comment]
Few things:
- do you already have working pi-hole in your LAN on another host? 
- containers won't be getting IPs from your local LAN DHCP range, only LMDS server as a single host will get an IP - only one IP. 
- containers if bridged will be reachable by LMDS host IP (plex is an example) such containers in Portainer will show no IP at all it means they use server IP itself on specific ports. 
- containers that using NATed Docker network (default one) getting internal IPs from range 172.18.0.x, again not from your LAN DHCP range. These containers can be reached by their specific ports and these ports can be remapped if needed, this is also why they are NATed internally. 
- pi-hole configuration I meant above is regarding so called "blocking lists" i.e. if jackett will be trying to reach a domain that is blocked by pi-hole request will timeout - this is nothing to do with IPs, it is all about DNS resolution at thsi point.       
- if you do have another pi-hole in your LAN do not deploy second one - you will be pointing your main router to forward DNS resolution to pi-hole in order for it to work at all, if you don't, pi-hole might work but will not perform any function anyway. 

I do not want to sound to harsch and I hope I am helping a little.

**Comment by bustedbyte** [comment]
First, Thanks! This is not harsh at all! All advice is helpful, its a pretty steep learning curve replacing a simple web instance of pi-hole and qBittorrent to this whole dockerized stack. Often things that may be quite obvious once you've done this before are completely alien the first time you see it.

My LMDS has an IP, a static one to allow my pi to take over DHCP and help control IP groups for people of different ages. Jackett has an internal IP set up To test the network, I tried running this command, I've been reading the docker man pages and playing some docker tutorials in the background while I have time.

`docker run jackett ping -c 192.203.230.10``

However I ended up with an error:

````
Unable to find image 'jackett:latest' locally
docker: Error response from daemon: pull access denied for jackett, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

I tried appending the DNS keys to Jackett per the initial post and at that point Jackett did start working and was able to resolve DNS again.

I would love to know a little more about how I could have run the above command. Once I figure this out, would you accept PR's to the site to add some notes for the "newb" user?
