### ISSUE TITLE
Add transmission-openvpn to menu

### ISSUE THREAD

**Issue by Adil-MohammedK** [GreenFrogSB/LMDS#16]

**Comment by GreenFrogSB** [comment]
There is a dedicated vpn container that should be used as a gateway for others, no matter if you use this or any other download client gateway container will work for them all. Including transmission with integrated vpn client would undermined an idea to have one solution feet all. 
If you really need this particular container in the stack just add it manually to the compose file in your deployment.

All the best GreenFrog
