### ISSUE TITLE
Adding Prowlarr to the stack

### ISSUE THREAD

**Issue by Rhfelwr** [GreenFrogSB/LMDS#19]
Hi, is it possible to add Prowlarr (Jackett alternative developed by the Sonarr/Radarr team) to the available containers?

**Comment by Rhfelwr** [comment]
Also the Radarr release plays nice with the stack now, no need to lock it to v5.14 (I think).

**Comment by GreenFrogSB** [comment]
Prowlarr  added to the stack.
Radarr set back to latest rather than 5.14 - hope it will work going forward as not always did.
