### ISSUE TITLE
Backup doesn't work

### ISSUE THREAD

**Issue by daniel-van-niekerk** [GreenFrogSB/LMDS#21]
When I choose Backup LMDS it return this message:

```
Containers not deployed yet
Nothing to backup
```

I've followed the guide and the docker images for Sonarr, Radarr, Deluge, Prowlarr and VPN is running and working just fine. I just want to do a normal backup, not rclone and gdrive.

**Comment by GreenFrogSB** [comment]
Please do exactly the same but not as root, just as pi user - it will work. 
It will only work if backup is ran by the user that holds LMDS folder in his home directory.  
When you run backup as i.e. root script is looking for LMDS data under /root/ directory and is not flinging anything.
Possibly warning message could be worded better - will adjust that in next release.

**Comment by daniel-van-niekerk** [comment]
It worked thanks! I was running around as root.

By the way, this tool is amazing.
