### ISSUE TITLE
sonarr container doesn't see the contents of /home/

### ISSUE THREAD

**Issue by goodpunk6** [GreenFrogSB/LMDS#25]
i'd love to point sonarr to my ~/LDMS/pi/media folder but sonarr doesn't see the contents of /home/. 

<img width="1511" alt="Screen Shot 2021-10-10 at 11 51 56 PM" src="https://user-images.githubusercontent.com/15090661/136730828-4fe95646-4f31-4542-ac3a-f0bab12f2767.png">

**Comment by GreenFrogSB** [comment]
Sonarr or any other container will only link your fost folder to what is
declared in docker-compose.yml file

in example, if you edit docker-compose.yml file located under /LMDS and
then navigate to sonarr declaration part, you will find section "volumes:"
and inside:

      - ./media/tvshows:/tv
      - ./downloads:/download

It means that the Raspbian OS folder /home/pi/LMDS/media/tvshow will be
seen by the sonarr container under /tv the same with
/home/pi/LMDS/media/downloads
and /download
This is your link between Raspbian OS and Sonarr container - I try to
explain this in the video about mounting an USB drive to LMDS.

I hope that helps.
