### ISSUE TITLE
Plex Server cannot start

### ISSUE THREAD

**Issue by Marvello** [GreenFrogSB/LMDS#26]
First of all thanks for all the work, it's really helpful for me to spawn my own local media server.

Not sure if this is a common issue or not, but I try to install Plex and it consistently gets `clock_gettime(CLOCK_MONOTONIC) failed: Operation not permitted` (attached the full logs [_plex_logs.txt](https://github.com/GreenFrogSB/LMDS/files/7398461/_plex_logs.txt))

Base on the guide [here ](https://www.youtube.com/watch?v=XudbMJ_3NRc&ab_channel=addicted2tech), I think you need to specify the image to use arm base like `ghcr.io/linuxserver/plex:arm32v7-latest` and add `privileged: true to make it works

**Comment by GreenFrogSB** [comment]
no longer the issue as far I was able to check
