### ISSUE TITLE
proper write permission set for file import

### ISSUE THREAD

**Issue by arifroni** [GreenFrogSB/LMDS#30]
hello

I followed all your information regarding setting up sonarr and radarr. i followed your instruction on how to mount NAS shares also. Here is my setup:

I mounted a single folder of my NAS to /mnt/smbshare. then linked smbshare both to ~/LMDS/media/movies and ~/LMDS/media/tvshows. 
my nas share contains 3 folders (there are some more), Movies, TV shows, and torrents. torrents folder receives files from seedbox.

So in sonarr setup is like this:

download client page's path config
remote path: /sdj/0110/downloads/completed/tv-sonarr-roni/
local path: /tv/torrents/tv-sonarr-roni/

media management root folder: /tv/TV_Series_WDMCHD

I am getting the following error 
![image](https://user-images.githubusercontent.com/59896374/153939981-e3809946-8171-4208-9e74-ae68988b33f1.png)

the path /sdj* is from seedbox and sonarr is supposed to look that in local path, which is /tv/torrents/tv-sonarr-roni/. And the file exist there!
I think it's a permission issue but can't figure out how to solve this. Does anyone have this issue?

**Comment by Wans22** [comment]
I have the same issue, do you have the answer ?

**Comment by arifroni** [comment]
> 

i fixed the problem, but dont really remember what change I needed to make. Can you please share the docker-compose.yaml. i can double-check with mine.

Also show me the output of "ls -la" in the following folders: docker, media, volumes

**Comment by Wans22** [comment]
Hi, sorry for taking so long to answer but now I have solved the problem.
I changed several times my operating system, I also changed of project because I was tired of it. But now it's work, I don't know why, but it works.
Thanks anyway for answering me
