### ISSUE TITLE
Can't use pihole dhcp server

### ISSUE THREAD

**Issue by Junn-Sorran** [GreenFrogSB/LMDS#39]
Hello,

It's not possible to use the dhcp service provided with the pihole in the stack due to the network configuration.
The official pihole documentation provide multiple solutions for this problem, do you think it would be possible to implement one with the stack?
https://docs.pi-hole.net/docker/dhcp/

Thanks!

**Comment by GreenFrogSB** [comment]
Hi Junn, 
Change implemented to the code as per article https://docs.pi-hole.net/docker/dhcp/
"Inside your docker-compose.yml remove all ports and replace them with: network_mode: host"
Pihole template updated

**Comment by Junn-Sorran** [comment]
That was fast thank you!
However i had to make the change manually in portainer to switch to host network? I pulled, updated and redeployed the stack but i kept the old configuration, do you know why?

**Comment by GreenFrogSB** [comment]
Yes, pull only update templates, therefore changes I make to the project do
not owerwrite users custom changes they did.

When you deploy or add/remove containers, script asks you to keep current
or update from template. If you choose to use template your changes will be
owerwritten with project defaults, this is also why it is not a default
option as in many cases you want to keep changes you made constant even if
I change a template at some point for whatever reason.

You should also change relevant files inside services folder to keep your
changes constant.

**Comment by Junn-Sorran** [comment]
Thank you it worked!

As a side note, can you add the LMD_BACKUP directory to the gitignore?
