### ISSUE TITLE
Running with Residential Proxies on same device

### ISSUE THREAD

**Issue by engageub** [GreenFrogSB/LMDS#40]
Hello,

Thank you for the app here. I have residential proxies and I would like to run it on multiple instances of earnapp on same device. Could you please let me know if it is possible currently or can I expect enhancements in future to proxify each instance. 

Thank you

**Comment by GreenFrogSB** [comment]
Hi, this sounds like a great idea at first glanc. As far I know earnapp, honeygain or IProylas etc. they are residential proxy providers, therefore using their own services to gain more IPs and use them sort of against each other to generate more traffic sounds promising. I also know that Honeygain has some mechanisms to detect VPN or cloud VPS usage and potentially they might detect other residental proxies use what could cause account suspension or being blocked. Having all that in mind I won't be trying to implement such a solution to the project.  
Thank you for throwing an idea here.
