### ISSUE TITLE
Fdisk shows me values that make no sense

### ISSUE THREAD

**Issue by Wans22** [GreenFrogSB/LMDS#42]
Hi, I open a new issue because I am following your tutorial (how to configure LMDS with an external USB drive) and I have a problem.
In your video, you make the command `fdisk -l` to give the information of the usb key but me, on my USB of 114G, the values are :

![Capture](https://user-images.githubusercontent.com/82324747/169660346-412760c5-4878-4deb-a459-97e856f6c8cc.PNG)

I do not understand however I made several formatting of which one of low level, in ntfs, there is thus no partition but it find 4 with strange capacities

I would need help to solve this problem, thanks in advance 👍

**Comment by GreenFrogSB** [comment]
Have you installed NTFS tools on Linux?
sudo apt-get install ntfs-3g

It seems that Linux does not recognize this device properly for some reason - partition structure there has no sense.

Value in 0xFF showing (BBT) means “Bad Block Table”, this is telling me that Linux see your storage device but is not able to work with the structure that is there. 
Use fdisk and format your device under Linux - maybe that will help.
