### ISSUE TITLE
Unable to get pihole web interface to register

### ISSUE THREAD

**Issue by bustedbyte** [GreenFrogSB/LMDS#43]
Feeling especially dense as I run through this. I had a perfectly running system but while looking at jackett, I ran into this sweet little system, and thought this would be a great upgrade from self installed hacked together monster I have. However, I've really been struggling with 2 things. 

1.   I have a pretty specific setup letting the pi take over my DCHP for my router and set up a series of static assignments and groups and blocks that are all safely backed up. Yet I can't even get the pihole gui to show up! It seems to be the only service without an internal IP and port.
2. I've added sonarr, radarr, deluge, jackett, I was going to add traefik for the sole purpose of allowing me to change things from 192.168.x.x:yyyy to sonarr.example.com, that would be the ideal setup. I've been through the articles, yet it seems like I'm the first to run into this issue. 

Feeling especially dense. Any advice would be welcome. Thanks.

**Comment by bustedbyte** [comment]
So it looks like part one of this issue is resolved. My browser seems to be optimized to autoforward that ipaddress on to https since my first attempt at traefik forwarded it, and somehow I can't clear that from memory. On another browser however I can get through locally and get into pi-hole properly.

Setting up traefik would be fabulous with with that configuration, but not a deal breaker. thanks for the great package!

**Comment by GreenFrogSB** [comment]
I am not sure if I follow your exact problem [#2] but if we are talking about traefik it should not be that complicated.
All what you do is to deploy the container and adjust few settings, like your domain name and its provider if you decide to use TLS verification or without it using https verification, Traefik should do all the rest with build in Let's Encrypt cert-bot. 
I try to make manual as clear as possible but it might be dense at first glance, plus traefik documentation is not the easiest to follow. It will be extremely difficult for me to help you without looking in to your config.

**Comment by bustedbyte** [comment]
I took off traefik but I'd be happy to put it back on and post anything you need. It's not exactly a top secret project, just doing some learning and household monitoring. There are times when it would be nice to access one of the tools internally or externally too!
