### ISSUE TITLE
Different Google Drive number in rclone instructions

### ISSUE THREAD

**Issue by ajkl2533** [GreenFrogSB/LMDS#45]
Seems that rclone changed the storage number in configuration for Google Drive. It's `13` now.

https://github.com/GreenFrogSB/LMDS/blob/0cd297c0c51e1bca80b9a7e5ab295c97956a5d06/deploy.sh#L536
```
echo -e "      [n] [gdrive] [13] [Enter] [Enter] [1] [Enter] [Enter] [n] [n]"

**Comment by GreenFrogSB** [comment]
code and web corrected - thank you Radek
