### ISSUE TITLE
jackett not accessible

### ISSUE THREAD

**Issue by chenks** [GreenFrogSB/LMDS#46]
got an issue with Jacket.
i have a clean install of Raspberry OS and LMDS.
followed the instructions to set up, installed Portainer and Jackett.

Portainer is running fine, but Jackett is not accessible on http://192.168.50.8:9117/
Portainer says Jackett is running but with no IP address or port

what have i done wrong?

![Screenshot 2022-07-15 133406](https://user-images.githubusercontent.com/11945919/179223929-d63c1272-121c-4f58-a0e8-54c1513cfe71.jpg)

**Comment by GreenFrogSB** [comment]
I assume you're doing all good.
Can you try to access Jackett using IP addres of your Raspberry Pi?
http://host_ip:9117

**Comment by GreenFrogSB** [comment]
Delete jackett container using Portainer. Edit docker-compose.yml file,
find section responsible for jackett, make sure it is set to :latest, save
the file and run docker-compose up -d --remove-orphans
This wiłl rebulind container, let me know if that works any better.

**Comment by GreenFrogSB** [comment]
Inside LMDS folder and LMDS folder is where you cloned it from github.

**Comment by chenks** [comment]
> Inside LMDS folder and LMDS folder is where you cloned it from github.

sorry, i edited my response with more details

**Comment by GreenFrogSB** [comment]
Hard fot me to help as I am on holidays and have only phone with me. Your docker-compose.yml is OK. Have you try simply restart entire Pi? I know this is a basic question and frustrating if you try already. No one else reported to me such issue latelly.

**Comment by chenks** [comment]
yes i have rebooted a few times.
i went and added 2 more containers, deluge and sabnzbd, and those are also exhibiting the same issues.

the only container that appears to be working is portainer.

**Comment by chenks** [comment]
currently testing it on a Pi Zero W, runing the latest Raspberry Pi OS Lite (32bit)

**Comment by GreenFrogSB** [comment]
Could you reimage SD card with 64bit Raspbian instead and try again.

**Comment by GreenFrogSB** [comment]
That might be the problem. Pi zero W, based on wiki has ARMv6Z (32-bit) CPU, containers are usually available for x86/64, ARMv7 and 8 platforms, sometimes just for arm with no version ie. Portainer is just ARM but Jackett is only available for x86/64, ARM7 and ARM8.
This should cause problem during pull reporting that container is not valid for your platform and I do not know why pull cause no issues for you.
It seems with this cpu you won't be able to use most of the containers.

**Comment by chenks** [comment]
looks like i'll need to try and get either a pi4 or pi zero w 2, although they appear to be non-existant at the moment to buy.

**Comment by chenks** [comment]
update - managed to pick up a Pi 4 Model B (2GB RAM), and all seems to be working correctly.

**Comment by chenks** [comment]
issue can be closed, issue was non-supported pi model.
