### ISSUE TITLE
Honeygain issue on Raspberry Pi 4

### ISSUE THREAD

**Issue by Dustymonster81** [GreenFrogSB/LMDS#48]
Hello! I used LMDS to make a docker that runs honeygain on my raspberry pi, but it does not work. If I start it, it keeps restarting forever. It is up for a second, then it starts restarting again.

**Comment by longhatdev** [comment]
Hi, i have the same problem. The log output is simply: 
``TOU are accepted 
Error processing authorisation``
but i am pretty sure to use the correct credentials in the installation process and also i see them in the `.templates/honeygain/service.yml` correctly.

It simply cant authorize correctly it seems.

thanks

**Comment by GreenFrogSB** [comment]
These two posts might be a defend issue.
Logs: `TOU are accepted Error processing authorisation` what that could mean?

I had that once for a very specific reason while testing. 

Let's say you deployed a HoneyGain container ok once and it got registered on dashboard with a specific name, then you removed this container - manually or using Portainer and then redeployed it again with the same username, password and also the same name - now you have an issue. 

Your initial container had hash generated that HoneyGain registered against _device name_ 
Now you deployed it again with different hash and trying to register it agains the same _device name_  
This is when I had `TOU are accepted Error processing authorisation` in my logs and container keeps rebooting. 

My solution was to change _device name_ to something that was not used before.

ie. in docker-compose.yml file find definition of HoneyGain container, you will see there your username, password and _-device_ 
change that name to something not used before, save the file and redeploy containers again using `docker-compose up -d`

example: 
from
command:  -tou-accept -email myemail@gmail.com -pass 87482382gdgw -device HoneyDocker1   
to
command:  -tou-accept -email myemail@gmail.com -pass 87482382gdgw -device HoneyDockerNew 

I hope that helps 

BTW: 
Above situation is seen by Honey Gain as cloning and you might be banned from the service if that continue.
Rebuilding existing container is ok but deploying new one with the same name previously registered is not ok
