### ISSUE TITLE
unbound container? Or pihole container with unbound built-in?

### ISSUE THREAD

**Issue by chenks** [GreenFrogSB/LMDS#52]
is it possible to add an unbound container that can be used with pihole, so we could use recursive DNS with pihole?
pihole works fine with the included docker image, but it's often better to use it with unbound.

**Comment by GreenFrogSB** [comment]
Will think about it in further releases, thank you request.

**Comment by chenks** [comment]
> Will think about it in further releases, thank you request.

would i have any issues if i removed the pihole container and just installed pihole and unbound direct on to the pi instead?
i'm guessing it wouldn't interfere with any of the docker containers?

I currently run in docker
radarr
sonarr
jackett
sabnzbd
deluge
portainer
