### ISSUE TITLE
How to use hardlink with sonarr and radarr instead of copying files

### ISSUE THREAD

**Issue by flodes80** [GreenFrogSB/LMDS#53]
Hello !

Small question, how can we use hardlinks instead of copying the files at each end of download with sonarr / radarr ?

Thanks in advance !

**Comment by GreenFrogSB** [comment]
You have to configure your download client to work with i.e. sonars. 
It all should move itself of its own from download location to i.e. sonarr.
Example configuration sonar and deluge as a download client: https://greenfrognest.com/lds.php#sonarrconfig 
Not sure what you mean by hardlinks on this occasion.

**Comment by flodes80** [comment]
Yes indeed but I don't want to move my torrents. I would like them to stay in my Torrent client (Transmission) to allow me to continue seeding.
So I think that Sonarr copies the files. But according to the Sonarr documentation and especially in the "media management" section in the options, we have the possibility to use "hardlinks" which are simply links from Unix. This would allow to create shortcuts to the media still in use by Transmission instead of copying them. But it doesn't seem to work. Is there a solution ? Thanks in advance !

Translated with www.DeepL.com/Translator (free version)
