### ISSUE TITLE
[Bug] Honeygain not working: Error processing authorisation

### ISSUE THREAD

**Issue by jgabriel98** [GreenFrogSB/LMDS#58]
Raspberry pi 4, raspbian bullseye lite - both 32 bit and 64 bit. 

`docker logs honeygain` shows:
TOU are accepted
Error processing authorisation

**Comment by GreenFrogSB** [comment]
Please check issue #48

**Comment by jgabriel98** [comment]
Checked it, 

The current honeygain dashboard shows these devices:
![image](https://user-images.githubusercontent.com/37881981/193952913-f982b5a8-7059-4b82-a5da-096a1d25e61e.png)

So, i've changed the device name, but still got same error:

 - first executed `$ docker run --privileged --rm tonistiigi/binfmt --install x86_64`
 - then 
 ``` bash
$ docker run -i --restart unless-stopped --platform linux/amd64 --name honeygain honeygain/honeygain -tou-accept -email censored@gmail.com -pass Mu0ig\)\!nla1 -device raspberrypi



  $$\   $$\                                                             $$\
  $$ |  $$ |                                                            \__|
  $$ |  $$ | $$$$$$\  $$$$$$$\   $$$$$$\  $$\   $$\  $$$$$$\   $$$$$$\  $$\ $$$$$$$\
  $$$$$$$$ |$$  __$$\ $$  __$$\ $$  __$$\ $$ |  $$ |$$  __$$\  \____$$\ $$ |$$  __$$\
  $$  __$$ |$$ /  $$ |$$ |  $$ |$$$$$$$$ |$$ |  $$ |$$ /  $$ | $$$$$$$ |$$ |$$ |  $$ |
  $$ |  $$ |$$ |  $$ |$$ |  $$ |$$   ____|$$ |  $$ |$$ |  $$ |$$  __$$ |$$ |$$ |  $$ |
  $$ |  $$ |\$$$$$$  |$$ |  $$ |\$$$$$$$\ \$$$$$$$ |\$$$$$$$ |\$$$$$$$ |$$ |$$ |  $$ |
  \__|  \__| \______/ \__|  \__| \_______| \____$$ | \____$$ | \_______|\__|\__|  \__|
                                          $$\   $$ |$$\   $$ |
                                          \$$$$$$  |\$$$$$$  |
                                           \______/  \______/

TOU are accepted
Error processing authorisation
```

##### About the password: i've shuffled it, but the above one contains the same charactes from the original. Also i've added (required so bash command wont break) `'\'` to symbols, turning `Mu0ig)!nla1` into `Mu0ig\)\!nla1`

-----------------------------------------------------

**\[context on why i manually ran the docker command\]**: I've found your repository from your comment on [this reddit thread](https://www.reddit.com/r/Honeygain/comments/tj8vfa/how_to_install_honeygain_on_a_raspberry_pi_with/).
And after taking a look into you code, i felt it would be better to run the docker command myself to facilitate debbuging.

But rest assure, that before executing manually, i tried to just run your scripts and got the same error.

**Comment by GreenFrogSB** [comment]
Just a quick check, as I am not able to verify from the picture attached,
how many HG instances you are trying to run on a single public IP - HG
allows only one device per IP at present.
I have to correct that on my website as it has changed since I wrote the
article some time ago.

**Comment by jgabriel98** [comment]
Yes, it was from the same IP. But 
 - even after disconnecting all devices,
![image](https://user-images.githubusercontent.com/37881981/194185877-b303373e-b39a-4cd4-a00c-249f5c77ceb2.png)
 - the same error persists :(
![image](https://user-images.githubusercontent.com/37881981/194185919-1e7e392d-0c8a-429f-a9ea-2e6365b37e73.png)
