### ISSUE TITLE
[BUG] Honeygain not working on raspberry pi 2 model b v1.1

### ISSUE THREAD

**Issue by xKliment** [GreenFrogSB/LMDS#59]
I have installed the Docker and it restarted after that i installed honeygain an logged in normally but its still not displaying in the dashboard after 12+hours

**Comment by xKliment** [comment]
I am using a raspberry pi 2 model b v1.1 with ubuntu server 20.04.05 LTS

**Comment by GreenFrogSB** [comment]
it won't run on raspberry pi 2 - as far I know this board is not 64bit
capable, what is needed to emulate x86 CPU for Honeygain on ARM.

**Comment by GreenFrogSB** [comment]
Checked in here: https://en.wikipedia.org/wiki/Raspberry_Pi
Raspberry 2 model B has - ARMv7 <https://en.wikipedia.org/wiki/ARMv7>-A
(32-bit)
Raspberry 2 model B version 1.2 has ARMv8
<https://en.wikipedia.org/wiki/ARMv8>-A (64/32-bit)
The second one should be ok but ARMv7-A  is not.

**Comment by xKliment** [comment]
Okay so i wont be able to run honeygain on it?
What would be the best way to fully deinstall everything?

**Comment by GreenFrogSB** [comment]
As far as I can see your older pi won't be able to run honeygain, but you
could try to run other bandwidth sharing apps included in LMDS.
Delete the LMDS folder and uninstall docker and docker-compose if you have
to.

**Comment by xKliment** [comment]
Thanks alot!

**Comment by xKliment** [comment]
Okay and how do i remove only the honeygain docker? Ive tried some stuff but it wont work!

**Comment by GreenFrogSB** [comment]
Run:
./deploy.sh
go to:
Build LMDS Stack
Scroll down and deselect first option called (remove asterisks)
[*] Check - Earn $ with LMDS - in main menu
[ ] Check - Earn $ with LMDS - in main menu
[ ] Check - Earn $ with LMDS - in main menu

Confirm selection with OK and run:
docker-compose up -d

**Comment by xKliment** [comment]
Wich programms would be able to run on the raspberry pi 2 model b v1.1?

**Comment by GreenFrogSB** [comment]
ARM 32bit capable are:
peer2profit - https://p2pr.me/164528477962110dab05459
earnapp - https://earnapp.com/i/snq8y4m

I do not have pi 2 myself so I was not able to test it myself but I believe
above will work ok.

**Comment by xKliment** [comment]
Okay thanks alot ill try! -
