### ISSUE TITLE
Can't connect servers on localhost or 127.0.0.1

### ISSUE THREAD

**Issue by csimpi** [GreenFrogSB/LMDS#6]
Hi,
thank you for this awesome script, I love it :)
I've successfully installed everything on my raspberry-pi, I can access the webUIs of the different services, but I can't connect them with using localhost. 
Most of them works using the device's network IP address, but that's not the desired way.

**Comment by GreenFrogSB** [comment]
Hi Peter,
Using Docker you won't be able to interconnect containers using localhost
or loopback IP, this will never work in Docker.
Think of docker container as a separate OS - kind of, it has a loopback to
itself but not to other containers.
You have to use host IP (raspberry Pi IP) or containers names if containers
are nated in one single network.
For ease of use, always use host IP and a port while connecting containers
together, every single container should be communicated with the other this
way.
Regards
GreenFrog

**Comment by csimpi** [comment]
@GreenFrogSB Thank you for your answer. In the meantime, I've realized this. But this is not the desired way to connect the different servers IMHO. I'm going to add static IP's to the containers and use those IPs to connect them.
