### ISSUE TITLE
Earn App pull URL Broken - 404 not found

### ISSUE THREAD

**Issue by Loggsie** [GreenFrogSB/LMDS#60]
Below error is received due to broken URL

_'Fetching aarch64
--2022-10-27 20:01:31--  https://brightdata.com/static/earnapp/aarch64
Resolving brightdata.com (brightdata.com)... 172.67.12.97, 104.22.26.189, 104.22.27.189
Connecting to brightdata.com (brightdata.com)|172.67.12.97|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-27 20:01:32 ERROR 404: Not Found.'_

Deploy script needs amending to pull from source 

wget -qO- https://brightdata.com/static/earnapp/install.sh > /tmp/earnapp.sh && sudo bash /tmp/earnapp.sh

**Comment by GreenFrogSB** [comment]
Corrected #60
