### ISSUE TITLE
NPMP - Cannot install php

### ISSUE THREAD

**Issue by bxlouis** [GreenFrogSB/LMDS#61]
Trying to deploy NPMP from the script, I ran into this error:

`ERROR: Service 'php7' failed to build: The command '/bin/sh -c apk update && apk add --no-cache     build-base shadow vim curl     php7     php7-fpm     php7-common     php7-pdo     php7-pdo_mysql     php7-mysqli     php7-mcrypt     php7-mbstring     php7-xml     php7-openssl     php7-json     php7-phar     php7-zip     php7-gd     php7-dom     php7-session     php7-zlib' returned a non-zero code: 17`

Looking it up online, I ended up on [this thread](https://github.com/docker-library/php/issues/1300) from the PHP container's git and I am concerned over [this](https://github.com/docker-library/php/issues/1300#issuecomment-1139138183) comment which says that one should not apk add php. 

Could you provide instructions to solve the issue and maybe change the way php is deployed considering this comment?

Thanks a lot for your work!

**Comment by GreenFrogSB** [comment]
NPMP Web Server was redone and will now use PHP CGI 8.2 - please pull changes down and redeploy. #68
