### ISSUE TITLE
HoneyGain Stops working after some hours

### ISSUE THREAD

**Issue by cripdk** [GreenFrogSB/LMDS#62]
Hello i'm trying to run honeygain on RPi 4 when i first install it was running but after some hours stop working and in the logs i'm getting this error "standard_init_linux.go:219: exec user process caused: exec format error". I try it again with doing all from a clean start and fresh OS but again the same thing running for some hours and then get the same error.

**Comment by GreenFrogSB** [comment]
This should be part of the script already but.....

Run this:
docker run --privileged --rm tonistiigi/binfmt --install x86_64 
then restart honeygain container. 

if above make container work ok, you will have to add this command to the crontab so it is run after every reboot. 
crontab -e 
pick an editor to modify the file and add the line below into it:
@reboot  docker run --privileged --rm tonistiigi/binfmt --install x86_64

Save it, it should make it work after reboot. 

I hope that helps.

**Comment by cripdk** [comment]
@GreenFrogSB  Thank you for your response, i tried that and after 10 days it seems that running with no problem so i think we fix it.
