### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by Cyb3r-N1nja** [GreenFrogSB/LMDS#65]
I tried installing this software using the instructions here:https://greenfrognest.com/lmdsondocker.php

but I keep getting error: ERROR: In file './docker-compose.yml', service must be a mapping, not a NoneType.

When I start installing the containers.

**Comment by GreenFrogSB** [comment]
This usually means that your yml file structure is incorrect - a white
space in the wrong place, too much or too little indentation in some line,
generally it is very likely a problem is in the structure of the file not
in its content. .
Can you attach your file here? do not copy paste content I need this exact
file. WinSCP should help you getting the file of the Linux system if you do
not know how.

**Comment by Cyb3r-N1nja** [comment]
I will try to reinstall it if the error appears again I will attach the file via WinSCP here.

**Comment by Cyb3r-N1nja** [comment]
Github doesnt support the filetyp.

but here is the dropbox link let me know if you could download it.

https://www.dropbox.com/s/c480rv1ui3janb7/docker-compose.yml?dl=0

**Comment by GreenFrogSB** [comment]
I believe I was able to see your file there - but there is nothing in it
except :

version: '2'services:

something is quite wrong as there is nothing to deploy there.

have you deploy, selected any containers for deployment ? if you did
there should be much more in this file than just above

**Comment by Cyb3r-N1nja** [comment]
ok I managed to fix it opening it in VSCode there where 5 additional lines which where causing the issue it works now :)
