### ISSUE TITLE
Stuck when ./deploy.sh

### ISSUE THREAD

**Issue by CroMoTho** [GreenFrogSB/LMDS#66]
Hello, when i try
        
~/LDS $ ./deploy.sh 

then i get this

checking for project update
Depuis https://github.com/GreenFrogSB/LDS
An update is available for the project

then nothing happen, i need to restart my terminal if i want to enter a new command

even
git reset --hard
and
git clean -fd
rm deploy.sh
git fetch --all
git reset --hard origin/main
git pull origin main

dont resolve the problem for me :( 

(Linux rockpi-4b 4.4.154-116-rockchip aarch64) 

please help

**Comment by GreenFrogSB** [comment]
Hmm I changed LDS to LMDS about two years ago - I would redeploy it fresh. 
You can backup volumes folder and docker-compose.yml file, then deploy LMDS fresh, copy over volumes folder back and compose file then run docker-compose up -d This will bring all back. Use separate SD card in case you run into problems.
