### ISSUE TITLE
[Request] Adding tdarr to LMDS

### ISSUE THREAD

**Issue by WolfBlader** [GreenFrogSB/LMDS#67]
Hello, is it possible to also add tdarr to LMDS ?
https://tdarr.io/

**Comment by GreenFrogSB** [comment]
I could add it but it might cause more problems than it will be solving.
Tdarr is great but is also very demanding to CPU and GPU if you have one on
the server.
Raspberry Pi is to slow to use it and as LMDS is mainly used by SBC's I
won't be adding it at this point.
Kind Regards
GreenFrog
