### ISSUE TITLE
Create minimal Raspberry Pi OS image with LMDS installed

### ISSUE THREAD

**Issue by m-roberts** [GreenFrogSB/LMDS#7]
It would be relatively straightforward to write a GitHub Action that would take the latest Raspberry Pi OS image, run your script, and then store the resulting OS image (as a GitHub Release, if desired).

This would make it easier for people to get started - an unexpanded Raspberry Pi OS Lite image with the tools preinstalled!

You can also have this run every few days/weeks to ensure that it remains up to date!

**Comment by GreenFrogSB** [comment]
Only upfront installation done on clean OS is a docker and docker-compose software, all the containers are modular depending on selection while runing the script. Prebuild OS would make more sense for more software dependent deployments. I went with docker and its modularity to avoid prebuild OS image. Thank you for suggestion, I really appreciate any suggestions.
