### ISSUE TITLE
bazarr container not working

### ISSUE THREAD

**Issue by Rhfelwr** [GreenFrogSB/LMDS#8]
So I deployed the stack as instructed, everything that I use works (Deluge/Sonarr/Radarr/Jackett) but for some reason bazarr refuses to allow me to connect to the WebUI. If I type the host IP xxx.xxx.x.xx:6767 it says "problem loading webpage". I tried re-deploying the stack with ./deploy.sh to no avail

**Comment by Rhfelwr** [comment]
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 40, in <module>
    from server import app, webserver
  File "/app/bazarr/bin/bazarr/server.py", line 83, in <module>
    webserver = Server()
  File "/app/bazarr/bin/bazarr/server.py", line 33, in __init__
    self.server = create_server(app,
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 81, in create_server
    last_serv = TcpWSGIServer(
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 239, in __init__
    self.bind_server_socket()
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 368, in bind_server_socket
    self.bind(sockaddr)
  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 398, in bind
    return self.socket.bind(addr)
OSError: [Errno 99] Address not available
Bazarr starting...
Bazarr exited.

I get this error when checking with docker logs bazarr. I tried assigning random port, assigning a different port to no avail. I changed UMASK_SET to UMASK in Env arguments as advised by Bazarr devs, no avail. I also tried rebuilding the entire stack by purging any downloaded image or trace of Bazarr. Didn't work either. I am at loss.

**Comment by GreenFrogSB** [comment]
I just deployed Bazarr this morning and all works ok for me - no problem accessing web UI. 
I saw you also opened a bug on Radarr GitHub page - let them look at it then.
I wont be able to fix container itself - if is not working, guys who created specific container have to look into it as I use their job pulling containers from Docker Hub.
You could try using older version of Bazarr if latest do not work for you.
It seems that latest Bazarr container works for me with no extra work, so it might be your specific system struggling with something there. 

This is my compose file section for Bazarr.
I can see that latest version is from 2 days so we use the same one you and me. 

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/bazarr/config:/config
      - ./media/movies:/movies
      - ./media/tvshows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

**Comment by Rhfelwr** [comment]
Hi I didn't open the Radarr issue only this one. Overnight my Pi disconnected from the ethernet for whatever reason killing my NAS mounts after reboot that the containers relied on, so I'll need to start installing the stack from scratch anyway... PITA. I'll report back if it works on a fresh setup.

**Comment by GreenFrogSB** [comment]
Yes, I meant Bazarr - https://github.com/linuxserver/docker-bazarr/issues/66 
Add your mounts into fstab so it is not lost after reboot. 
Let me know. if somehow it is back working after re-deployment.

**Comment by Rhfelwr** [comment]
After a fresh reinstall bazarr works perfectly. Just a tip btw regarding LMDS, I’d place the movies/tv and downloads into the same path as otherwise Sonarr/Radarr has a hard time moving completed files out of the Deluge download folder (as they see /downloads as a separate filesystem from /media/tv and /media/movies).
